name: "Terraform Automation"
on:
  push:
    branches:
      - main # Change if using a different branch
permissions:
  contents: read
  id-token: write
jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Login to Azure
        run: |
          echo "🔄 Logging into Azure..."
          
          # Validate that secrets are set
          if [[ -z "${{ secrets.AZURE_CLIENT_ID }}" || -z "${{ secrets.AZURE_CLIENT_SECRET }}" || -z "${{ secrets.AZURE_TENANT_ID }}" ]]; then
            echo "❌ ERROR: One or more Azure secrets are missing!"
            exit 1
          fi
          
          # Authenticate with Azure
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
